// Workspace seeding — `airglow install` materializes the managed workspace
// content into AIRGLOW_HOME and installs baseline dependencies.
//
// Managed-overwrite policy: everything in the seed tree (shared/, docs/,
// AGENTS.md, airglow.d.ts, scripts/) is vendored — force-overwritten on every
// install so updates propagate; agents are told to copy-not-edit. Exceptions
// are SEED_IF_ABSENT (user may legitimately edit: extra root deps, tsconfig
// tweaks) and apps/, which is user space and never touched.
//
// Asset source: compiled binaries read the embedded src/seed-assets.json
// (generated by scripts/pack-seed.ts at build time); source runs read the
// repo checkout directly so edits don't need a repack.
//
// `bun install` runs via the binary itself (BUN_BE_BUN=1 turns a compiled
// Bun executable back into the plain bun CLI) — end-user machines need no
// separate bun/node install.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { AIRGLOW_HOME, STATE_DIR } from './paths';
import { HOST_VERSION } from './version';
import type { SeedTree } from './seed-files';

// Which binary version last seeded the workspace. `airglow install` and the
// daemon's startup check both go through seedWorkspace, which stamps this —
// so a self-updated binary re-seeds managed docs on its first boot.
export const SEEDED_VERSION_PATH = join(STATE_DIR, 'seeded-version');

export function seededVersion(): string {
  try { return readFileSync(SEEDED_VERSION_PATH, 'utf8').trim(); } catch { return ''; }
}

const SEED_IF_ABSENT = new Set(['package.json', 'tsconfig.json']);

async function loadSeedTree(): Promise<SeedTree> {
  if (Bun.main.includes('$bunfs')) {
    // Generated by scripts/pack-seed.ts before every build; absent in a fresh
    // checkout (gitignored), hence the ts-ignore.
    // @ts-ignore
    return (await import('./seed-assets.json')).default as SeedTree;
  }
  const { collectSeedFromRepo } = await import('./seed-files');
  return collectSeedFromRepo(join(import.meta.dir, '..'));
}

export async function seedWorkspace(): Promise<void> {
  const tree = await loadSeedTree();
  mkdirSync(join(AIRGLOW_HOME, 'apps'), { recursive: true });

  let written = 0;
  let kept = 0;
  let pkgCreated = false;
  for (const [rel, file] of Object.entries(tree)) {
    const dest = join(AIRGLOW_HOME, rel);
    const exists = existsSync(dest);
    if (exists && SEED_IF_ABSENT.has(rel)) {
      kept++;
      continue;
    }
    const next = file.e === 'b64' ? Buffer.from(file.c, 'base64') : Buffer.from(file.c, 'utf8');
    if (exists && Buffer.compare(readFileSync(dest), next) === 0) {
      kept++;
      continue;
    }
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, next);
    written++;
    if (rel === 'package.json' && !exists) pkgCreated = true;
  }
  console.log(`workspace ${AIRGLOW_HOME}: ${written} file(s) seeded, ${kept} up to date`);
  try { writeFileSync(SEEDED_VERSION_PATH, `${HOST_VERSION}\n`); } catch {}

  if (pkgCreated || !existsSync(join(AIRGLOW_HOME, 'node_modules'))) {
    console.log('installing workspace dependencies…');
    const proc = Bun.spawn([process.execPath, 'install'], {
      cwd: AIRGLOW_HOME,
      env: { ...process.env, BUN_BE_BUN: '1' },
      stdout: 'inherit',
      stderr: 'inherit',
    });
    if ((await proc.exited) !== 0) {
      console.error(`dependency install failed — run \`airglow\`'s bundled bun manually: BUN_BE_BUN=1 ${process.execPath} install (in ${AIRGLOW_HOME})`);
    }
  }
}
