#!/usr/bin/env node
// Installs the Chrome native messaging manifest for the Airglow debug bridge.
// Idempotent: safe to run on every `airglow dev`.
//
// Generates a per-machine launcher script with the absolute path to the node
// binary that ran this installer (process.execPath), so Chrome — which inherits
// a sparse PATH from launchd/the desktop session — can still find node.
//
// Writes the manifest into every known Chromium-variant NM dir whose parent
// directory exists on this machine; new browsers installed later are picked up
// on the next `airglow dev` start.
//
// Supported: macOS, Linux. WSL works only when Chrome/Chromium runs inside WSL
// (Windows-side Chrome reads NM manifests from the Windows registry).
//
// Usable two ways:
//   1. CLI:    node install.mjs
//   2. Import: import { installNativeHost } from './install.mjs'; installNativeHost();

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const HOST_NAME = 'com.airglow.trace';
const EXTENSION_ID = 'comikpjjijckpjkobpkkpnnhlcpmagic'; // derived from pinned manifest.key

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Per-platform NM directories per Chromium variant. The fork name is just a
// label for logging; what matters is the parent existing (= browser installed).
function manifestDirs() {
  const home = os.homedir();
  if (process.platform === 'darwin') {
    const base = path.join(home, 'Library/Application Support');
    return [
      ['Chrome',    `${base}/Google/Chrome`],
      ['Chromium',  `${base}/Chromium`],
      ['Brave',     `${base}/BraveSoftware/Brave-Browser`],
      ['Edge',      `${base}/Microsoft Edge`],
      ['Vivaldi',   `${base}/Vivaldi`],
      ['Opera',     `${base}/com.operasoftware.Opera`],
      ['Yandex',    `${base}/Yandex/YandexBrowser`],
      ['Arc',       `${base}/Arc/User Data`],
    ].map(([name, parent]) => ({ name, dir: path.join(parent, 'NativeMessagingHosts') }));
  }
  if (process.platform === 'linux') {
    const base = path.join(home, '.config');
    return [
      ['Chrome',    `${base}/google-chrome`],
      ['Chromium',  `${base}/chromium`],
      ['Brave',     `${base}/BraveSoftware/Brave-Browser`],
      ['Edge',      `${base}/microsoft-edge`],
      ['Vivaldi',   `${base}/vivaldi`],
      ['Opera',     `${base}/opera`],
      ['Yandex',    `${base}/yandex-browser`],
    ].map(([name, parent]) => ({ name, dir: path.join(parent, 'NativeMessagingHosts') }));
  }
  return [];
}

// Write a launcher script with the absolute node path baked in. Chrome inherits
// a sparse PATH on macOS (launchd) and often on Linux desktops, so /usr/bin/env
// node may fail to resolve even when node is installed.
function writeLauncher(quiet) {
  const launcher = path.join(__dirname, 'host-launcher.sh');
  const host = path.join(__dirname, 'host.mjs');
  const next =
    `#!/bin/bash\n` +
    `# Generated by install.mjs — do not edit. Regenerated each \`airglow dev\` start.\n` +
    `exec ${shellQuote(process.execPath)} ${shellQuote(host)} "$@"\n`;
  let current = null;
  try { current = fs.readFileSync(launcher, 'utf8'); } catch {}
  if (current !== next) {
    fs.writeFileSync(launcher, next);
    if (!quiet) console.log(`[airglow] wrote launcher ${launcher} (node: ${process.execPath})`);
  }
  fs.chmodSync(launcher, 0o755);
  return launcher;
}

function shellQuote(s) { return `'${s.replace(/'/g, `'\\''`)}'`; }

export function installNativeHost({ quiet = false, extraDirs = [] } = {}) {
  if (process.platform !== 'darwin' && process.platform !== 'linux') {
    if (!quiet) console.error(`[airglow] native host install: ${process.platform} not supported`);
    return { installed: 0, skipped: true };
  }

  try { fs.chmodSync(path.join(__dirname, 'host.mjs'), 0o755); } catch {}
  const launcher = writeLauncher(quiet);

  const manifest = {
    name: HOST_NAME,
    description: 'Airglow extension debug bridge (logs, reload)',
    path: launcher,
    type: 'stdio',
    allowed_origins: [`chrome-extension://${EXTENSION_ID}/`],
  };

  // Auto-detected browser dirs: skip those whose parent (= browser data dir) is
  // absent, signalling the user doesn't have that browser. extraDirs (e.g. a
  // workspace-local user-data-dir from `pnpm chrome`) are written unconditionally.
  const auto = manifestDirs().filter(({ dir }) => fs.existsSync(path.dirname(dir)));
  const dirs = [...auto, ...extraDirs.map((dir) => ({ name: 'custom', dir }))];

  let installed = 0;
  for (const { name, dir } of dirs) {
    try {
      fs.mkdirSync(dir, { recursive: true });
      const file = path.join(dir, `${HOST_NAME}.json`);
      const next = JSON.stringify(manifest, null, 2);
      let current = null;
      try { current = fs.readFileSync(file, 'utf8'); } catch {}
      if (current !== next) {
        fs.writeFileSync(file, next);
        if (!quiet) console.log(`[airglow] installed native host manifest for ${name} at ${file}`);
        installed++;
      }
    } catch (e) {
      if (!quiet) console.error(`[airglow] failed to install at ${dir}: ${e.message}`);
    }
  }
  return { installed, skipped: false };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  installNativeHost();
}
